server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:h2:mem:test_db;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
    initialization-mode: always
    schema:
      - classpath:schema-sys.sql
    data:
      - classpath:data-auth.sql
      - classpath:data-user.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
application:
  login:
    single: true