spring:
  datasource:
    url: jdbc:h2:mem:test_db;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
    initialization-mode: always
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
application:
  login:
    single: true